import { chromium } from '@playwright/test';
const b = await chromium.launch(); const p = await b.newPage();
const t0 = Date.now(); const log = (m) => console.log(((Date.now()-t0)/1000).toFixed(2), m);
p.on('request', r => { if (!/\.(png|jpg|css|js|woff2?|svg|gif)(\?|$)/.test(r.url()) && r.url().includes('automationexercise')) log(`REQ ${r.method()} ${r.resourceType()} ${r.url()}`); });
p.on('dialog', d => { log(`DIALOG ${d.type()} ${d.message()}`); d.accept(); });
await p.goto('https://automationexercise.com/contact_us', { waitUntil: 'domcontentloaded' }); log('dcl');
await p.getByPlaceholder('Email', { exact: true }).fill(`qa.net.${Date.now()}@example.com`);
log('click'); await p.getByRole('button', { name: 'Submit' }).click(); log('clicked');
await p.locator('#contact-page').getByText('Success!').waitFor(); log('success ' + p.url()); await p.waitForTimeout(4000); log('end');
await b.close();
